version: 2.1
orbs:
  node: circleci/node@4.7
  docker: circleci/docker@1.7.0

jobs:
  build-and-push:
    environment:
      DOCKER_IMAGE: hitechqb/circleci-web
      DOCKER_TAG: latest
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check:
          docker-username: DOCKER_USERNAME
          docker-password: DOCKER_PASSWORD
      - docker/build:
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"

  deploy:
    # Please add $SSH_KEY_FINGERPRINT, $DEPLOYED_USER@ and DEPLOYED_SERVER to project's environment
    executor: docker/docker
    steps:
      - add_ssh_keys:
          fingerprints:
            - $SSH_KEY_CIRCLE_CI
      - run: ssh -oStrictHostKeyChecking=no $USERNAME_CIRCLE_CI@$IP_SERVER_GCLOUD ./deploy.sh
workflows:
  my-pipeline:
    jobs:
      - node/test
      - build-and-push:
          requires:
            - node/test
          filters:
            branches:
              only:
                - master
#      - deploy:
#          requires:
#            - build-and-push

